//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlusUltra {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class sublime_text_2 : global::System.Configuration.ApplicationSettingsBase {
        
        private static sublime_text_2 defaultInstance = ((sublime_text_2)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new sublime_text_2())));
        
        public static sublime_text_2 Default {
            get {
                return defaultInstance;
            }
        }
    }
}
